resource "aws_autoscaling_group" "autoscaling_group" {
  #(Optional) Name of the Auto Scaling Group. By default generated by Terraform. Conflicts with name_prefix.
  name = var.name
  #(Optional) Name of the launch configuration to use.
  launch_configuration = aws_launch_configuration.launch_configuration.name
  #(Optional) List of subnet IDs to launch resources in. Subnets automatically determine which availability zones the group will reside. Conflicts with availability_zones.
  vpc_zone_identifier = var.subnets

  #(Required) Minimum size of the Auto Scaling Group. (See also Waiting for Capacity below.)
  min_size = var.cluster_min_size
  #(Required) Maximum size of the Auto Scaling Group.
  max_size = var.cluster_max_size
  #(Optional) Number of Amazon EC2 instances that should be running in the group. (See also Waiting for Capacity below.)
  desired_capacity = var.cluster_desired_capacity

  tag {
    key                 = "Name"
    value               = "ecs-${var.name}"
    propagate_at_launch = true
  }
  tag {
    key                 = "Environment"
    value               = var.environment
    propagate_at_launch = true
  }
  tag {
    key                 = "TerraformManaged"
    value               = "true"
    propagate_at_launch = true
  }
}

